{% set name = "pydiso" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 336494e121afa169f2da25c5faa00785251ac8c7ebe3c98e120cc89b30ab447d

build:
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
  host:
    - python
    - pip
    - mkl-devel
    - cython
    - numpy
    - meson
    - meson-python
    - setuptools_scm
  run:
    - python
    - scipy >=0.13
  run_constrained:
    # Block openmp from being installed in the same environment (conflicts with numpy and MKL)
    # done by giving an unsatisfiable openmp version.
    # Note: llvm-openmp is safe though.
    - openmp ==99999999999999

test:
  imports:
    - pydiso
    - pydiso.mkl_solver

about:
  home: https://github.com/simpeg/pydiso
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple cython based interface to the pardiso solver'

extra:
  recipe-maintainers:
    - jcapriot
    - lheagy
