{% set name = "pydiso" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d17c6c73422abcf812bfdca9b2e4082778d6c1d2b8102304e0e41877c3d44c26

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
  host:
    - python
    - pip
    - mkl-devel
    - cython
    - numpy
    - meson
    - meson-python
    - setuptools_scm
  run:
    - python
    - scipy >=0.13

test:
  imports:
    - pydiso
    - pydiso.mkl_solver

about:
  home: https://github.com/simpeg/pydiso
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple cython based interface to the pardiso solver'

extra:
  recipe-maintainers:
    - jcapriot
    - lheagy
